name: Continuous Integration

on:
  push:
    paths:
      - "*.cs"
      - "*.csproj"

jobs:
  
  name: "Source Compilation"
  runs-on: ubuntu-latest
  container: mcr.microsoft.com/dotnet/core/sdk:3.1
  steps:
    - name: "Checkout Code"
      uses: actions/checkout@v1
    - name: "Compile Source"
      run: dotnet build Source/ProtoStar.Collections.csproj
  
